testing inline test-cov & roxygen

diff --git a/.github/workflows/containers-and-az-pool.yaml b/.github/workflows/containers-and-az-pool.yaml
--- a/.github/workflows/containers-and-az-pool.yaml
+++ b/.github/workflows/containers-and-az-pool.yaml
@@ -5,7 +5,6 @@ name: Create Docker Image and Azure Pool
 
 on:
   workflow_dispatch:
-  workflow_call:
   pull_request:
     paths-ignore: # we don't need this to run everytime we make an edit to an irrelevant file
       - .github/workflows/block-fixup.yaml
@@ -35,57 +34,88 @@ env:
   # Together, these form: cfaprdbatchcr.azurecr.io/cfa-epinow2-pipeline
   REGISTRY: cfaprdbatchcr.azurecr.io/
   IMAGE_NAME: cfa-epinow2-pipeline
+  IMAGE_TAG: ${{ (github.head_ref || github.ref_name) == 'main' && 'latest' || github.head_ref || github.ref_name }}
 
 jobs:
 
   build-pipeline-image:
-    permissions:
-      id-token: write # This is required for requesting the JWT
-      contents: read  # This is required for actions/checkout
-      packages: write # This is required for ACR import
     runs-on: ubuntu-latest
     name: Build image
-
     outputs:
-      tag: ${{ steps.image-tag.outputs.tag }}
+      ghcr-image: ghcr.io/cdcgov/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
 
     steps:
 
       - name: Checkout code
         uses: actions/checkout@v4
 
-      # From: https://stackoverflow.com/a/58035262/2097171
-      - name: Extract branch name
-        shell: bash
-        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
-        id: branch-name
-
-      #########################################################################
-      # Getting the tag
-      # The tag will be used for both the docker image and the batch pool
-      #########################################################################
-      - name: Figure out tag (either latest if it is main or the branch name)
-        shell: bash
-        id: image-tag
-        run: |
-          if [ "${{ steps.branch-name.outputs.branch }}" = "main" ]; then
-            echo "tag=latest" >> $GITHUB_OUTPUT
-          else
-            echo "tag=${{ steps.branch-name.outputs.branch }}" >> $GITHUB_OUTPUT
-          fi
-
       - name: Docker Login
         uses: docker/login-action@v3
         with:
-
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Docker build and push
         run: |
-          chmod +x $GITHUB_WORKSPACE/.github/scripts/docker_build_and_push.sh
-          $GITHUB_WORKSPACE/.github/scripts/docker_build_and_push.sh ${{ env.IMAGE_NAME }} ${{ steps.image-tag.outputs.tag }}
+          IMAGE="ghcr.io/cdcgov/${{ env.IMAGE_NAME }}"
+          TAG=${{ env.IMAGE_TAG }}
+          BUILDER=docker-container-driver-builder
+
+          # create a builder with the docker-container driver to allow cache-export
+          docker buildx create --name "$BUILDER" --driver=docker-container || true
+
+          # use the registry cache for prior images of the same tag, or the 'latest' tag
+          docker buildx build --push -t "$IMAGE:$TAG" \
+                  --builder "$BUILDER" \
+                  --cache-from "type=registry,ref=$IMAGE:$TAG-cache" \
+                  --cache-from "type=registry,ref=$IMAGE:latest-cache" \
+                  --cache-to "type=registry,ref=$IMAGE:$TAG-cache,mode=max" \
+                  -f Dockerfile .
+
+  check-roxygen:
+    needs: build-pipeline-image
+    runs-on: ubuntu-latest
+    container:
+      image: ${{ needs.build-pipeline-image.outputs.ghcr-image }}
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Check that roxygen documentation is up to date
+        run: |
+          git config --global --add safe.directory "$GITHUB_WORKSPACE"
+          Rscript -e "roxygen2::roxygenize()"
+          git diff --exit-code man || (echo "::error::Documentation is not up to date. Run 'roxygen2::roxygenize()' locally to re-render." && exit 1)
+
+  code-coverage:
+    needs: build-pipeline-image
+    runs-on: ubuntu-latest
+    container:
+      image: ${{ needs.build-pipeline-image.outputs.ghcr-image }}
+    steps:
+      - uses: actions/checkout@v4
+      - name: Test coverage
+        shell: Rscript {0}
+        run: |
+          covr::codecov(
+            quiet = FALSE,
+            clean = FALSE,
+            token = "${{ secrets.CODECOV_TOKEN }}"
+          )
+
+      - name: Show testthat output
+        if: always()
+        run: |
+          ## --------------------------------------------------------------------
+          find . -name 'testthat.Rout*' -exec cat '{}' \; || true
+        shell: bash
+
+      - name: Upload test results
+        if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverage-test-failures
+          path: ${{ runner.temp }}/package
 
   acr-import:
     needs: build-pipeline-image
@@ -97,8 +127,6 @@ jobs:
       packages: write # This is required for ACR import
 
     name: Copy image from GHCR to ACR
-    outputs:
-      tag: ${{ needs.build-pipeline-image.outputs.tag }}
     steps:
 
       # From: https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#requesting-the-jwt-using-the-actions-core-toolkit
@@ -128,7 +156,7 @@ jobs:
             --federated-token ${{ steps.idtoken.outputs.id_token }} \
             --output none
 
-            IMAGE_TAG=${{ env.IMAGE_NAME }}:${{ needs.build-pipeline-image.outputs.tag }}
+            IMAGE_TAG=${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
             az acr import --name ${{ env.REGISTRY }} \
               --source "ghcr.io/cdcgov/$IMAGE_TAG" \
               --username ${{ github.actor }} \
@@ -149,18 +177,6 @@ jobs:
     permissions:
       contents: read
       id-token: write
-
-    env:
-      TAG: ${{ needs.acr-import.outputs.tag }}
-      # Every Azure Batch Pool parameter can simply go here,
-      # no python module or config toml necessary
-      POOL_ID: "cfa-epinow2-${{ needs.acr-import.outputs.tag }}"
-      BATCH_ACCOUNT:     "cfaprdba"
-      BATCH_ENDPOINT:    "https://cfaprdba.eastus.batch.azure.com/"
-      NODE_AGENT_SKU_ID: "batch.node.ubuntu 22.04"
-      VM_SIZE:           "standard_d4d_v5"
-      RESOURCE_GROUP:    ${{ secrets.PRD_RESOURCE_GROUP }}
-      BATCH_SUBNET_ID:   ${{ secrets.BATCH_SUBNET_ID }}
 
     steps:
       - name: Checkout Repo
@@ -206,8 +222,8 @@ jobs:
             export CONTAINER_REGISTRY_USERNAME=${{ secrets.CONTAINER_REGISTRY_USERNAME }}
             export CONTAINER_REGISTRY_PASSWORD=${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
             export CONTAINER_REGISTRY_URL=${{ secrets.CONTAINER_REGISTRY_URL }}
-            export CONTAINER_IMAGE_NAME=${{ env.REGISTRY }}${{ env.IMAGE_NAME }}:${{ env.TAG }}
-            export POOL_ID=${{ env.POOL_ID }}
+            export CONTAINER_IMAGE_NAME=${{ env.REGISTRY }}${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
+            export POOL_ID=cfa-epinow2-${{ env.IMAGE_TAG }}
             export SUBNET_ID=${{ secrets.BATCH_SUBNET_ID }}
             export RESOURCE_GROUP=${{ secrets.RESOURCE_GROUP }}
 
