Moving from self-hosted runner to ubuntu-latest + runner-action (#277)

diff --git a/.github/workflows/delete-container-tag.yaml b/.github/workflows/delete-container-tag.yaml
--- a/.github/workflows/delete-container-tag.yaml
+++ b/.github/workflows/delete-container-tag.yaml
@@ -40,28 +40,51 @@ jobs:
     continue-on-error: true # allow other tag deletion to happen even if one fails
     permissions:
       id-token: write
-      contents: read
-    runs-on: cfa-cdcgov-aca
+    runs-on: ubuntu-latest
     name: Delete image tag from ACR
 
     steps:
-      - name : Checkout code
-        uses: actions/checkout@v4
-
-      - name: Login to Azure with NNH Service Principal using OIDC
-        id: azure_login_2
-        uses: azure/login@v2
-        with:
-          # managed by EDAV. Contact Amit Mantri or Jon Kislin if you
-          # have issues. Also, this is documented in the Predict
-          # handbook.
-          client-id: ${{ secrets.AZURE_NNHT_SP_CLIENT_ID }}
-          tenant-id: ${{ secrets.TENANT_ID }}
-          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
-
-      - name: Azure CLI script
+      - name: Protect 'latest'
         run: |
-            bash $GITHUB_WORKSPACE/.github/scripts/delete-container-tag.sh \
-              ${{ secrets.CONTAINER_REGISTRY_URL }} \
-              ${{ env.IMAGE_NAME }} \
-              ${{ env.IMAGE_TAG }}
+          if [ "${{ env.IMAGE_TAG }}" = "latest" ]; then
+            echo "Cannot delete pool for 'latest'"
+            exit 1
+          fi
+
+      # From: https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#requesting-the-jwt-using-the-actions-core-toolkit
+      - name: Install OIDC Client from Core Package
+        run: npm install @actions/core@1.6.0 @actions/http-client
+      - name: Get Id Token
+        uses: actions/github-script@v7
+        id: idtoken
+        with:
+          script: |
+            const coredemo = require('@actions/core')
+            const id_token = await coredemo.getIDToken('api://AzureADTokenExchange')
+            coredemo.setOutput('id_token', id_token)
+
+      - name: Delete ACR tag
+        uses: CDCgov/cfa-actions/runner-action@v1.3.0
+        with:
+          github_app_id: ${{ secrets.CDCENT_ACTOR_APP_ID }}
+          github_app_pem: ${{ secrets.CDCENT_ACTOR_APP_PEM }}
+          wait_for_completion: true
+          print_logs: true
+          script: |
+              CURRENT_BRANCH='${{ github.event.pull_request.head.sha || github.ref_name }}'
+              echo "Cloning repo at commit '$CURRENT_BRANCH'"
+              git clone -b $CURRENT_BRANCH https://github.com/${{ github.repository }}.git
+              cd ${{ github.event.repository.name }}
+
+              echo "Logging into Azure CLI"
+              az login --service-principal \
+                --username ${{ secrets.AZURE_NNHT_SP_CLIENT_ID }} \
+                --tenant ${{ secrets.TENANT_ID }} \
+                --federated-token ${{ steps.idtoken.outputs.id_token }} \
+                --output none
+
+              echo "Running delete tag script"
+              bash .github/scripts/delete-container-tag.sh \
+                ${{ secrets.CONTAINER_REGISTRY_URL }} \
+                ${{ env.IMAGE_NAME }} \
+                ${{ env.IMAGE_TAG }}
